[package]
name = "scylla"
version = "0.5.0"
edition = "2021"
description = "Async CQL driver for Rust, optimized for Scylla, fully compatible with Apache Cassandra™"
repository = "https://github.com/scylladb/scylla-rust-driver"
readme = "../README.md"
keywords = ["database", "scylla", "cql", "cassandra"]
categories = ["database"]
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
defaults = []
ssl = ["tokio-openssl", "openssl"]

[dependencies]
scylla-macros = { version = "0.1.1", path = "../scylla-macros"}
scylla-cql = { version = "0.0.1", path = "../scylla-cql"}
byteorder = "1.3.4"
bytes = "1.0.1"
futures = "0.3.6"
histogram = "0.6.9"
num_enum = "0.5"
tokio = { version = "1.12", features = ["net", "time", "io-util", "sync", "rt", "macros"] }
snap = "1.0"
uuid = "1.0"
rand = "0.8.3"
thiserror = "1.0"
itertools = "0.10.0"
bigdecimal = "0.2.0"
num-bigint = "0.3"
tracing = "0.1.25"
chrono = "0.4.20"
openssl = { version = "0.10.32", optional = true }
tokio-openssl = { version = "0.6.1", optional = true }
arc-swap = "1.3.0"
dashmap = "5.2"
strum = "0.23"
strum_macros = "0.23"
lz4_flex = { version = "0.9.2" }
smallvec = "1.8.0"
async-trait = "0.1.56"
anyhow = "1.0.65"
string = "0.3.0"

[dev-dependencies]
criterion = "0.3"
tracing-subscriber = "0.3.14"
assert_matches = "1.5.0"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name = "plop"
path = "src/plop.rs"